import {
  User,
  Session,
  Participant,
  Equipe,
  Inscription,
  QCMEvaluation,
  ReflectiveEvaluation,
  ExperientialEvaluation,
  JuryDecision,
  Document,
  Alert,
} from './types';

// Utilisateurs mockés
export const mockUsers: User[] = [
  {
    id: '1',
    name: 'Admin Principal',
    email: 'admin@scyfco.fr',
    role: 'Admin',
  },
  {
    id: '2',
    name: 'Marie Dupont',
    email: 'marie.dupont@scyfco.fr',
    role: 'DS',
  },
  {
    id: '3',
    name: 'Jean Martin',
    email: 'jean.martin@scyfco.fr',
    role: 'Mentor',
  },
  {
    id: '4',
    name: 'Sophie Bernard',
    email: 'sophie.bernard@scyfco.fr',
    role: 'Jury',
  },
];

// Sessions mockées
export const mockSessions: Session[] = [
  {
    id: 'S001',
    title: 'Certification Développeur Full Stack - Promo 2026-01',
    description: 'Formation intensive sur les technologies web modernes',
    status: 'En cours',
    startDate: '2026-01-06',
    endDate: '2026-03-31',
    location: 'Paris - Campus Innovation',
    nps: 8.5,
    completionRate: 78,
    participantCount: 24,
    mentorId: '3',
    dsId: '2',
  },
  {
    id: 'S002',
    title: 'Certification Data Analyst - Promo 2026-01',
    description: 'Analyse de données et visualisation',
    status: 'En cours',
    startDate: '2026-01-13',
    endDate: '2026-04-15',
    location: 'Lyon - Centre Formation',
    nps: 9.1,
    completionRate: 85,
    participantCount: 18,
    mentorId: '3',
    dsId: '2',
  },
  {
    id: 'S003',
    title: 'Certification DevOps Engineer - Promo 2025-12',
    description: 'Infrastructure as Code et CI/CD',
    status: 'Terminée',
    startDate: '2025-12-01',
    endDate: '2025-12-20',
    location: 'Bordeaux - TechHub',
    nps: 8.8,
    completionRate: 92,
    participantCount: 15,
    mentorId: '3',
    dsId: '2',
  },
  {
    id: 'S004',
    title: 'Certification UX/UI Designer - Promo 2026-02',
    description: 'Design thinking et prototypage',
    status: 'Planifiée',
    startDate: '2026-02-03',
    endDate: '2026-04-30',
    location: 'Lille - Digital Lab',
    participantCount: 20,
    mentorId: '3',
    dsId: '2',
  },
  {
    id: 'S005',
    title: 'Workshop JavaScript Avancé',
    description: 'Formation courte sur ES6+ et frameworks modernes',
    status: 'Planifiée',
    startDate: '2026-01-20',
    endDate: '2026-01-24',
    location: 'Paris - Campus Innovation',
    participantCount: 12,
    mentorId: '3',
    dsId: '2',
  },
  {
    id: 'S006',
    title: 'Certification Cloud Architecture AWS',
    description: 'Architecture et services cloud Amazon',
    status: 'En cours',
    startDate: '2026-01-15',
    endDate: '2026-02-28',
    location: 'Toulouse - Tech Center',
    nps: 8.9,
    completionRate: 80,
    participantCount: 16,
    mentorId: '3',
    dsId: '2',
  },
  {
    id: 'S007',
    title: 'Formation Scrum Master',
    description: 'Méthodologies agiles et gestion de projet',
    status: 'Planifiée',
    startDate: '2026-01-27',
    endDate: '2026-01-31',
    location: 'Nantes - Innovation Hub',
    participantCount: 14,
    mentorId: '3',
    dsId: '2',
  },
  {
    id: 'S008',
    title: 'Cybersécurité - Niveau 1',
    description: 'Fondamentaux de la sécurité informatique',
    status: 'Annulée',
    startDate: '2026-01-08',
    endDate: '2026-01-12',
    location: 'Marseille - Security Lab',
    participantCount: 0,
    mentorId: '3',
    dsId: '2',
  },
];

// Équipes mockées (par session)
export const mockEquipes: Equipe[] = [
  // Session S001 - Certification Développeur Full Stack
  {
    id: 'EQ001',
    nom: 'Équipe Alpha',
    sessionId: 'S001',
    mentorId: '3',
    description: 'Équipe orientée backend et API',
  },
  {
    id: 'EQ002',
    nom: 'Équipe Beta',
    sessionId: 'S001',
    mentorId: '3',
    description: 'Équipe orientée frontend et UX',
  },
  // Session S002 - Certification Data Analyst
  {
    id: 'EQ003',
    nom: 'Équipe Gamma',
    sessionId: 'S002',
    mentorId: '3',
    description: 'Équipe data visualisation',
  },
  // Session S003 - Certification DevOps Engineer
  {
    id: 'EQ004',
    nom: 'Équipe Delta',
    sessionId: 'S003',
    mentorId: '3',
    description: 'Équipe infrastructure et déploiement',
  },
  // Session S006 - Certification Cloud Architecture AWS
  {
    id: 'EQ005',
    nom: 'Équipe Cloud',
    sessionId: 'S006',
    mentorId: '3',
    description: 'Équipe architecture cloud',
  },
];

// Inscriptions mockées (relation entre participant, session et équipe)
export const mockInscriptions: Inscription[] = [
  {
    id: 'INS001',
    participantId: 'P001',
    sessionId: 'S001',
    equipeId: 'EQ001',
    status: 'Actif',
    dateInscription: '2025-12-15',
    qcmScore: 85,
    qcmStatus: 'Validée',
    reflectiveStatus: 'Complète',
    experientialStatus: 'En cours',
    decisionStatus: 'En attente',
  },
  {
    id: 'INS002',
    participantId: 'P002',
    sessionId: 'S001',
    equipeId: 'EQ001',
    status: 'Actif',
    dateInscription: '2025-12-16',
    qcmScore: 92,
    qcmStatus: 'Validée',
    reflectiveStatus: 'Validée',
    experientialStatus: 'Complète',
    decisionStatus: 'Validé',
  },
  {
    id: 'INS003',
    participantId: 'P003',
    sessionId: 'S001',
    equipeId: 'EQ002',
    status: 'Actif',
    dateInscription: '2025-12-14',
    qcmScore: 68,
    qcmStatus: 'Complète',
    reflectiveStatus: 'En cours',
    experientialStatus: 'À compléter',
    decisionStatus: 'En attente',
  },
  {
    id: 'INS004',
    participantId: 'P004',
    sessionId: 'S001',
    equipeId: 'EQ002',
    status: 'Actif',
    dateInscription: '2025-12-17',
    qcmScore: 78,
    qcmStatus: 'Validée',
    reflectiveStatus: 'Complète',
    experientialStatus: 'En cours',
    decisionStatus: 'En attente',
  },
  {
    id: 'INS005',
    participantId: 'P005',
    sessionId: 'S002',
    equipeId: 'EQ003',
    status: 'Actif',
    dateInscription: '2026-01-05',
    qcmScore: 88,
    qcmStatus: 'Validée',
    reflectiveStatus: 'Validée',
    experientialStatus: 'Validée',
    decisionStatus: 'Validé',
  },
  {
    id: 'INS006',
    participantId: 'P006',
    sessionId: 'S002',
    equipeId: 'EQ003',
    status: 'Actif',
    dateInscription: '2026-01-06',
    qcmScore: 95,
    qcmStatus: 'Validée',
    reflectiveStatus: 'Complète',
    experientialStatus: 'En cours',
    decisionStatus: 'En attente',
  },
  {
    id: 'INS007',
    participantId: 'P007',
    sessionId: 'S001',
    equipeId: 'EQ001',
    status: 'Inscrit',
    dateInscription: '2026-01-02',
    qcmStatus: 'À compléter',
    reflectiveStatus: 'À compléter',
    experientialStatus: 'À compléter',
    decisionStatus: 'En attente',
  },
  {
    id: 'INS008',
    participantId: 'P008',
    sessionId: 'S003',
    equipeId: 'EQ004',
    status: 'Certifié',
    dateInscription: '2025-11-20',
    qcmScore: 90,
    qcmStatus: 'Validée',
    reflectiveStatus: 'Validée',
    experientialStatus: 'Validée',
    decisionStatus: 'Validé',
  },
  // Inscriptions multiples pour le même participant (P001 - Alexandre Dubois)
  {
    id: 'INS009',
    participantId: 'P001',
    sessionId: 'S002',
    equipeId: 'EQ003',
    status: 'Actif',
    dateInscription: '2026-01-03',
    qcmScore: 75,
    qcmStatus: 'Validée',
    reflectiveStatus: 'En cours',
    experientialStatus: 'À compléter',
    decisionStatus: 'En attente',
  },
  // Deuxième inscription pour P002 - Camille Rousseau
  {
    id: 'INS010',
    participantId: 'P002',
    sessionId: 'S006',
    equipeId: 'EQ005',
    status: 'Actif',
    dateInscription: '2026-01-10',
    qcmScore: 88,
    qcmStatus: 'Validée',
    reflectiveStatus: 'Complète',
    experientialStatus: 'En cours',
    decisionStatus: 'En attente',
  },
  // Troisième inscription pour P001 - Alexandre Dubois (session terminée)
  {
    id: 'INS011',
    participantId: 'P001',
    sessionId: 'S003',
    equipeId: 'EQ004',
    status: 'Certifié',
    dateInscription: '2025-11-18',
    qcmScore: 92,
    qcmStatus: 'Validée',
    reflectiveStatus: 'Validée',
    experientialStatus: 'Validée',
    decisionStatus: 'Validé',
  },
  // Deuxième inscription pour P003 - Thomas Petit
  {
    id: 'INS012',
    participantId: 'P003',
    sessionId: 'S006',
    equipeId: 'EQ005',
    status: 'Actif',
    dateInscription: '2026-01-12',
    qcmStatus: 'À compléter',
    reflectiveStatus: 'À compléter',
    experientialStatus: 'À compléter',
    decisionStatus: 'En attente',
  },
];

// Participants mockés
export const mockParticipants: Participant[] = [
  {
    id: 'P001',
    firstName: 'Alexandre',
    lastName: 'Dubois',
    email: 'alexandre.dubois@example.com',
    phone: '06 12 34 56 78',
    sessionId: 'S001',
    teamName: 'Équipe Alpha',
    status: 'Actif',
    qcmScore: 85,
    qcmStatus: 'Validée',
    reflectiveStatus: 'Complète',
    experientialStatus: 'En cours',
    decisionStatus: 'En attente',
    enrollmentDate: '2025-12-15',
  },
  {
    id: 'P002',
    firstName: 'Camille',
    lastName: 'Rousseau',
    email: 'camille.rousseau@example.com',
    phone: '06 23 45 67 89',
    sessionId: 'S001',
    teamName: 'Équipe Alpha',
    status: 'Actif',
    qcmScore: 92,
    qcmStatus: 'Validée',
    reflectiveStatus: 'Validée',
    experientialStatus: 'Complète',
    decisionStatus: 'Validé',
    enrollmentDate: '2025-12-16',
  },
  {
    id: 'P003',
    firstName: 'Thomas',
    lastName: 'Petit',
    email: 'thomas.petit@example.com',
    phone: '06 34 56 78 90',
    sessionId: 'S001',
    teamName: 'Équipe Beta',
    status: 'Actif',
    qcmScore: 68,
    qcmStatus: 'Complète',
    reflectiveStatus: 'En cours',
    experientialStatus: 'À compléter',
    decisionStatus: 'En attente',
    enrollmentDate: '2025-12-14',
  },
  {
    id: 'P004',
    firstName: 'Léa',
    lastName: 'Moreau',
    email: 'lea.moreau@example.com',
    phone: '06 45 67 89 01',
    sessionId: 'S001',
    teamName: 'Équipe Beta',
    status: 'Actif',
    qcmScore: 78,
    qcmStatus: 'Validée',
    reflectiveStatus: 'Complète',
    experientialStatus: 'En cours',
    decisionStatus: 'En attente',
    enrollmentDate: '2025-12-17',
  },
  {
    id: 'P005',
    firstName: 'Lucas',
    lastName: 'Simon',
    email: 'lucas.simon@example.com',
    phone: '06 56 78 90 12',
    sessionId: 'S002',
    teamName: 'Équipe Gamma',
    status: 'Actif',
    qcmScore: 88,
    qcmStatus: 'Validée',
    reflectiveStatus: 'Validée',
    experientialStatus: 'Validée',
    decisionStatus: 'Validé',
    enrollmentDate: '2026-01-05',
  },
  {
    id: 'P006',
    firstName: 'Emma',
    lastName: 'Laurent',
    email: 'emma.laurent@example.com',
    phone: '06 67 89 01 23',
    sessionId: 'S002',
    teamName: 'Équipe Gamma',
    status: 'Actif',
    qcmScore: 95,
    qcmStatus: 'Validée',
    reflectiveStatus: 'Complète',
    experientialStatus: 'En cours',
    decisionStatus: 'En attente',
    enrollmentDate: '2026-01-06',
  },
  {
    id: 'P007',
    firstName: 'Hugo',
    lastName: 'Lefebvre',
    email: 'hugo.lefebvre@example.com',
    phone: '06 78 90 12 34',
    sessionId: 'S001',
    teamName: 'Équipe Alpha',
    status: 'En attente',
    qcmStatus: 'À compléter',
    reflectiveStatus: 'À compléter',
    experientialStatus: 'À compléter',
    decisionStatus: 'En attente',
    enrollmentDate: '2026-01-02',
  },
  {
    id: 'P008',
    firstName: 'Chloé',
    lastName: 'Roux',
    email: 'chloe.roux@example.com',
    phone: '06 89 01 23 45',
    sessionId: 'S003',
    teamName: 'Équipe Delta',
    status: 'Certifié',
    qcmScore: 90,
    qcmStatus: 'Validée',
    reflectiveStatus: 'Validée',
    experientialStatus: 'Validée',
    decisionStatus: 'Validé',
    enrollmentDate: '2025-11-20',
  },
];

// Évaluations QCM mockées
export const mockQCMEvaluations: QCMEvaluation[] = [
  {
    id: 'QCM001',
    participantId: 'P001',
    score: 85,
    maxScore: 100,
    completedAt: '2026-01-07T14:30:00Z',
    questions: [
      {
        id: 'Q1',
        question: 'Quelle est la différence entre let et const en JavaScript?',
        userAnswer: 'const ne peut pas être réassigné',
        correctAnswer: 'const ne peut pas être réassigné',
        isCorrect: true,
      },
      {
        id: 'Q2',
        question: 'Qu\'est-ce que le DOM?',
        userAnswer: 'Document Object Model',
        correctAnswer: 'Document Object Model',
        isCorrect: true,
      },
      {
        id: 'Q3',
        question: 'Qu\'est-ce qu\'une Promise en JavaScript?',
        userAnswer: 'Un objet asynchrone',
        correctAnswer: 'Un objet représentant une valeur future',
        isCorrect: false,
      },
    ],
  },
  {
    id: 'QCM002',
    participantId: 'P002',
    score: 92,
    maxScore: 100,
    completedAt: '2026-01-07T15:00:00Z',
    questions: [
      {
        id: 'Q1',
        question: 'Quelle est la différence entre let et const en JavaScript?',
        userAnswer: 'const ne peut pas être réassigné',
        correctAnswer: 'const ne peut pas être réassigné',
        isCorrect: true,
      },
      {
        id: 'Q2',
        question: 'Qu\'est-ce que le DOM?',
        userAnswer: 'Document Object Model',
        correctAnswer: 'Document Object Model',
        isCorrect: true,
      },
      {
        id: 'Q3',
        question: 'Qu\'est-ce qu\'une Promise en JavaScript?',
        userAnswer: 'Un objet représentant une valeur future',
        correctAnswer: 'Un objet représentant une valeur future',
        isCorrect: true,
      },
    ],
  },
];

// Évaluations réflexives mockées
export const mockReflectiveEvaluations: ReflectiveEvaluation[] = [
  {
    id: 'REF001',
    participantId: 'P001',
    status: 'Complète',
    submittedAt: '2026-01-08T10:00:00Z',
    responses: [
      {
        id: 'R1',
        question: 'Décrivez votre projet principal et les technologies utilisées',
        answer: 'J\'ai développé une application e-commerce avec React, Node.js et PostgreSQL...',
        mentorComment: 'Très bonne compréhension des concepts. Continuez ainsi!',
      },
      {
        id: 'R2',
        question: 'Quelles difficultés avez-vous rencontrées et comment les avez-vous surmontées?',
        answer: 'La gestion d\'état avec Redux était complexe au début...',
        mentorComment: 'Excellente analyse de vos challenges.',
      },
    ],
  },
  {
    id: 'REF002',
    participantId: 'P002',
    status: 'Validée',
    submittedAt: '2026-01-08T11:30:00Z',
    responses: [
      {
        id: 'R1',
        question: 'Décrivez votre projet principal et les technologies utilisées',
        answer: 'Application de gestion de tâches avec Next.js et TypeScript...',
        mentorComment: 'Excellent travail!',
      },
      {
        id: 'R2',
        question: 'Quelles difficultés avez-vous rencontrées et comment les avez-vous surmontées?',
        answer: 'TypeScript était nouveau pour moi mais j\'ai rapidement appris...',
        mentorComment: 'Très bonne capacité d\'adaptation.',
      },
    ],
  },
];

// Évaluations expérientielles mockées
export const mockExperientialEvaluations: ExperientialEvaluation[] = [
  {
    id: 'EXP001',
    participantId: 'P001',
    status: 'En cours',
    evaluatedAt: '2026-01-08T14:00:00Z',
    overallScore: 75,
    criteria: [
      {
        id: 'C1',
        name: 'Autonomie',
        description: 'Capacité à travailler de manière indépendante',
        score: 8,
        maxScore: 10,
        comment: 'Très autonome, cherche des solutions par soi-même',
      },
      {
        id: 'C2',
        name: 'Collaboration',
        description: 'Travail en équipe et communication',
        score: 7,
        maxScore: 10,
        comment: 'Bonne communication, peut encore progresser',
      },
      {
        id: 'C3',
        name: 'Qualité du code',
        description: 'Respect des standards et bonnes pratiques',
        score: 8,
        maxScore: 10,
        comment: 'Code propre et bien documenté',
      },
    ],
  },
  {
    id: 'EXP002',
    participantId: 'P002',
    status: 'Complète',
    evaluatedAt: '2026-01-08T15:00:00Z',
    overallScore: 90,
    criteria: [
      {
        id: 'C1',
        name: 'Autonomie',
        description: 'Capacité à travailler de manière indépendante',
        score: 9,
        maxScore: 10,
        comment: 'Excellente autonomie',
      },
      {
        id: 'C2',
        name: 'Collaboration',
        description: 'Travail en équipe et communication',
        score: 9,
        maxScore: 10,
        comment: 'Excellente collaboration',
      },
      {
        id: 'C3',
        name: 'Qualité du code',
        description: 'Respect des standards et bonnes pratiques',
        score: 9,
        maxScore: 10,
        comment: 'Code exemplaire',
      },
    ],
  },
];

// Décisions jury mockées
export const mockJuryDecisions: JuryDecision[] = [
  {
    id: 'JD001',
    participantId: 'P002',
    status: 'Validé',
    submittedAt: '2026-01-08T09:00:00Z',
    validatedAt: '2026-01-08T16:00:00Z',
    decision: 'Certifié',
    juryMember: 'Sophie Bernard',
    comments: 'Excellent parcours, toutes les compétences validées',
  },
  {
    id: 'JD002',
    participantId: 'P001',
    status: 'En attente',
    submittedAt: '2026-01-08T10:00:00Z',
    comments: 'Dossier en cours de révision',
  },
  {
    id: 'JD003',
    participantId: 'P005',
    status: 'Validé',
    submittedAt: '2026-01-07T14:00:00Z',
    validatedAt: '2026-01-07T18:00:00Z',
    decision: 'Certifié',
    juryMember: 'Sophie Bernard',
    comments: 'Très bon niveau, certification accordée',
  },
];

// Documents mockés
export const mockDocuments: Document[] = [
  {
    id: 'DOC001',
    type: 'Certificat',
    title: 'Certificat SCYFCO - Camille Rousseau',
    participantId: 'P002',
    sessionId: 'S001',
    generatedAt: '2026-01-08T17:00:00Z',
    generatedBy: 'Admin Principal',
    url: '/documents/certificat-P002.pdf',
  },
  {
    id: 'DOC002',
    type: 'Attestation',
    title: 'Attestation de présence - Session S001',
    sessionId: 'S001',
    generatedAt: '2026-01-08T09:00:00Z',
    generatedBy: 'Marie Dupont',
    url: '/documents/attestation-S001.pdf',
  },
  {
    id: 'DOC003',
    type: 'Rapport',
    title: 'Rapport d\'évaluation - Alexandre Dubois',
    participantId: 'P001',
    sessionId: 'S001',
    generatedAt: '2026-01-08T14:00:00Z',
    generatedBy: 'Jean Martin',
    url: '/documents/rapport-P001.pdf',
  },
];

// Alertes mockées
export const mockAlerts: Alert[] = [
  {
    id: 'A001',
    type: 'warning',
    title: 'Évaluation en attente',
    message: '3 évaluations expérientielles sont en attente de validation',
    createdAt: '2026-01-08T08:00:00Z',
    read: false,
  },
  {
    id: 'A002',
    type: 'info',
    title: 'Nouvelle session planifiée',
    message: 'La session S004 démarre le 3 février 2026',
    createdAt: '2026-01-07T15:00:00Z',
    read: false,
  },
  {
    id: 'A003',
    type: 'error',
    title: 'QCM incomplet',
    message: 'Hugo Lefebvre n\'a pas complété son QCM (délai: 2 jours)',
    createdAt: '2026-01-08T10:00:00Z',
    read: false,
  },
  {
    id: 'A004',
    type: 'success',
    title: 'Certification validée',
    message: 'Camille Rousseau a obtenu sa certification',
    createdAt: '2026-01-08T16:30:00Z',
    read: true,
  },
];
